title: Maker404
description: Project Not Found? We’ve Got You.
baseurl: "" # the subpath of your site
url: "https://maker404.com"

theme: minima
plugins:
  - jekyll-feed

collections:
  challenges:
    output: true
    permalink: /404-challenges/:title/
